"use strict";

window.QR_EFFECT_LIBRARY = {
  categories: [
    {
      id: "core",
      name: "Base",
      description: "Effetti affidabili e versatili."
    },
    {
      id: "neon",
      name: "Neon",
      description: "Effetti luminosi e digitali."
    },
    {
      id: "premium",
      name: "Premium",
      description: "Effetti raffinati e professionali."
    },
    {
      id: "creative",
      name: "Creative",
      description: "Effetti fortemente riconoscibili."
    }
  ],

  effects: [
    {
      id: "bubble",
      name: "Bubble",
      category: "core",
      icon: "●",
      description: "Punti morbidi blu e ciano.",
      dotsType: "dots",
      dotsColor1: "#0B3F8C",
      dotsColor2: "#00C2FF",
      gradientType: "radial",
      gradientRotation: "45",
      cornersSquareType: "dot",
      cornersDotType: "dot",
      cornersColor1: "#07346F",
      cornersColor2: "#00B7E8",
      useCornersGradient: true,
      backgroundColor1: "#FFFFFF",
      backgroundColor2: "#EAF8FF",
      backgroundGradientType: "radial",
      backgroundOpacity: "100"
    },

    {
      id: "pixel",
      name: "Pixel",
      category: "core",
      icon: "▦",
      description: "Pixel netti e tecnici.",
      dotsType: "square",
      dotsColor1: "#111827",
      dotsColor2: "#111827",
      gradientType: "solid",
      gradientRotation: "0",
      cornersSquareType: "square",
      cornersDotType: "square",
      cornersColor1: "#111827",
      cornersColor2: "#111827",
      useCornersGradient: false,
      backgroundColor1: "#FFFFFF",
      backgroundColor2: "#FFFFFF",
      backgroundGradientType: "solid",
      backgroundOpacity: "100"
    },

    {
      id: "liquid",
      name: "Liquid",
      category: "core",
      icon: "◉",
      description: "Morbido, fluido, verde acqua.",
      dotsType: "classy-rounded",
      dotsColor1: "#005C43",
      dotsColor2: "#1DD1A1",
      gradientType: "linear",
      gradientRotation: "130",
      cornersSquareType: "extra-rounded",
      cornersDotType: "dot",
      cornersColor1: "#004430",
      cornersColor2: "#30E7B2",
      useCornersGradient: true,
      backgroundColor1: "#FFFFFF",
      backgroundColor2: "#E9FFF8",
      backgroundGradientType: "radial",
      backgroundOpacity: "100"
    },

    {
      id: "glitch",
      name: "Glitch",
      category: "core",
      icon: "≋",
      description: "Viola, rosa e ciano digitale.",
      dotsType: "square",
      dotsColor1: "#2D0B59",
      dotsColor2: "#FF007A",
      gradientType: "linear",
      gradientRotation: "45",
      cornersSquareType: "square",
      cornersDotType: "square",
      cornersColor1: "#1E063D",
      cornersColor2: "#00E5FF",
      useCornersGradient: true,
      backgroundColor1: "#FFFFFF",
      backgroundColor2: "#FFF0FA",
      backgroundGradientType: "linear",
      backgroundOpacity: "100"
    },

    {
      id: "mono",
      name: "Mono",
      category: "core",
      icon: "◐",
      description: "Monocromatico affidabile.",
      dotsType: "rounded",
      dotsColor1: "#1D1D1D",
      dotsColor2: "#1D1D1D",
      gradientType: "solid",
      gradientRotation: "0",
      cornersSquareType: "extra-rounded",
      cornersDotType: "dot",
      cornersColor1: "#1D1D1D",
      cornersColor2: "#1D1D1D",
      useCornersGradient: false,
      backgroundColor1: "#FFFFFF",
      backgroundColor2: "#FFFFFF",
      backgroundGradientType: "solid",
      backgroundOpacity: "100"
    },

    {
      id: "contrast",
      name: "Contrast",
      category: "core",
      icon: "◑",
      description: "Blu navy e giallo sole.",
      dotsType: "extra-rounded",
      dotsColor1: "#071A52",
      dotsColor2: "#FFD400",
      gradientType: "linear",
      gradientRotation: "90",
      cornersSquareType: "square",
      cornersDotType: "square",
      cornersColor1: "#041139",
      cornersColor2: "#FFE466",
      useCornersGradient: true,
      backgroundColor1: "#FFFFFF",
      backgroundColor2: "#FFFCEA",
      backgroundGradientType: "radial",
      backgroundOpacity: "100"
    },

    {
      id: "soft",
      name: "Soft",
      category: "core",
      icon: "◌",
      description: "Lavanda delicata e moderna.",
      dotsType: "classy-rounded",
      dotsColor1: "#5146A8",
      dotsColor2: "#C095FF",
      gradientType: "linear",
      gradientRotation: "45",
      cornersSquareType: "extra-rounded",
      cornersDotType: "dot",
      cornersColor1: "#40368C",
      cornersColor2: "#D4B5FF",
      useCornersGradient: true,
      backgroundColor1: "#FFFFFF",
      backgroundColor2: "#F7F0FF",
      backgroundGradientType: "radial",
      backgroundOpacity: "100"
    },

    {
      id: "neon",
      name: "Neon",
      category: "neon",
      icon: "✦",
      description: "Magenta e viola neon.",
      dotsType: "classy-rounded",
      dotsColor1: "#5A0CA8",
      dotsColor2: "#F000B8",
      gradientType: "linear",
      gradientRotation: "90",
      cornersSquareType: "extra-rounded",
      cornersDotType: "dot",
      cornersColor1: "#440782",
      cornersColor2: "#FF21CC",
      useCornersGradient: true,
      backgroundColor1: "#FFFFFF",
      backgroundColor2: "#FBEAFF",
      backgroundGradientType: "radial",
      backgroundOpacity: "100"
    },

    {
      id: "matrix",
      name: "Matrix",
      category: "neon",
      icon: "▣",
      description: "Verde digitale e pixel square.",
      dotsType: "square",
      dotsColor1: "#003B12",
      dotsColor2: "#39FF14",
      gradientType: "linear",
      gradientRotation: "90",
      cornersSquareType: "square",
      cornersDotType: "square",
      cornersColor1: "#00280C",
      cornersColor2: "#5CFF3B",
      useCornersGradient: true,
      backgroundColor1: "#FFFFFF",
      backgroundColor2: "#ECFFEA",
      backgroundGradientType: "radial",
      backgroundOpacity: "100"
    },

    {
      id: "laser-pink",
      name: "Laser Pink",
      category: "neon",
      icon: "✹",
      description: "Fucsia laser e viola profondo.",
      dotsType: "classy-rounded",
      dotsColor1: "#5F00B5",
      dotsColor2: "#FF00B8",
      gradientType: "linear",
      gradientRotation: "110",
      cornersSquareType: "extra-rounded",
      cornersDotType: "dot",
      cornersColor1: "#3B0074",
      cornersColor2: "#FF33CD",
      useCornersGradient: true,
      backgroundColor1: "#FFFFFF",
      backgroundColor2: "#FFF0FC",
      backgroundGradientType: "radial",
      backgroundOpacity: "100"
    },

    {
      id: "cyber",
      name: "Cyber",
      category: "neon",
      icon: "⌁",
      description: "Navy e lime cyberpunk.",
      dotsType: "dots",
      dotsColor1: "#081B33",
      dotsColor2: "#A6FF00",
      gradientType: "linear",
      gradientRotation: "115",
      cornersSquareType: "square",
      cornersDotType: "dot",
      cornersColor1: "#071426",
      cornersColor2: "#9BEB00",
      useCornersGradient: true,
      backgroundColor1: "#FFFFFF",
      backgroundColor2: "#F6FFE8",
      backgroundGradientType: "radial",
      backgroundOpacity: "100"
    },

    {
      id: "aurora",
      name: "Aurora",
      category: "neon",
      icon: "✧",
      description: "Indaco e verde acqua aurora.",
      dotsType: "rounded",
      dotsColor1: "#3B1E91",
      dotsColor2: "#1DD1A1",
      gradientType: "linear",
      gradientRotation: "140",
      cornersSquareType: "extra-rounded",
      cornersDotType: "dot",
      cornersColor1: "#2B1474",
      cornersColor2: "#29E1B0",
      useCornersGradient: true,
      backgroundColor1: "#FFFFFF",
      backgroundColor2: "#EEFDF8",
      backgroundGradientType: "radial",
      backgroundOpacity: "100"
    },

    {
      id: "gold",
      name: "Gold",
      category: "premium",
      icon: "◆",
      description: "Nero e oro, showroom e luxury.",
      dotsType: "square",
      dotsColor1: "#101010",
      dotsColor2: "#B88915",
      gradientType: "linear",
      gradientRotation: "135",
      cornersSquareType: "square",
      cornersDotType: "square",
      cornersColor1: "#0A0A0A",
      cornersColor2: "#BE8A14",
      useCornersGradient: true,
      backgroundColor1: "#FFFFFF",
      backgroundColor2: "#FFF9E7",
      backgroundGradientType: "linear",
      backgroundOpacity: "100"
    },

    {
      id: "copper",
      name: "Copper",
      category: "premium",
      icon: "◈",
      description: "Rame e antracite per architettura.",
      dotsType: "square",
      dotsColor1: "#252525",
      dotsColor2: "#C77742",
      gradientType: "linear",
      gradientRotation: "135",
      cornersSquareType: "square",
      cornersDotType: "square",
      cornersColor1: "#1B1B1B",
      cornersColor2: "#D58D56",
      useCornersGradient: true,
      backgroundColor1: "#FFFFFF",
      backgroundColor2: "#FFF5ED",
      backgroundGradientType: "linear",
      backgroundOpacity: "100"
    },

    {
      id: "emerald",
      name: "Emerald",
      category: "premium",
      icon: "⬥",
      description: "Verde smeraldo e oro.",
      dotsType: "extra-rounded",
      dotsColor1: "#005C43",
      dotsColor2: "#D4A62A",
      gradientType: "linear",
      gradientRotation: "45",
      cornersSquareType: "extra-rounded",
      cornersDotType: "dot",
      cornersColor1: "#004430",
      cornersColor2: "#E1B83D",
      useCornersGradient: true,
      backgroundColor1: "#FFFFFF",
      backgroundColor2: "#FFF9E7",
      backgroundGradientType: "radial",
      backgroundOpacity: "100"
    },

    {
      id: "midnight",
      name: "Midnight",
      category: "premium",
      icon: "◼",
      description: "Blu notte e metallo cromato.",
      dotsType: "square",
      dotsColor1: "#0B1220",
      dotsColor2: "#7C8797",
      gradientType: "linear",
      gradientRotation: "135",
      cornersSquareType: "square",
      cornersDotType: "square",
      cornersColor1: "#080D16",
      cornersColor2: "#A8B2C1",
      useCornersGradient: true,
      backgroundColor1: "#FFFFFF",
      backgroundColor2: "#EEF2F6",
      backgroundGradientType: "linear",
      backgroundOpacity: "100"
    },

    {
      id: "platinum",
      name: "Platinum",
      category: "premium",
      icon: "◇",
      description: "Nero e platino tecnico.",
      dotsType: "square",
      dotsColor1: "#151515",
      dotsColor2: "#AEB7C2",
      gradientType: "linear",
      gradientRotation: "130",
      cornersSquareType: "square",
      cornersDotType: "square",
      cornersColor1: "#0C0C0C",
      cornersColor2: "#C7D0D9",
      useCornersGradient: true,
      backgroundColor1: "#FFFFFF",
      backgroundColor2: "#F1F4F6",
      backgroundGradientType: "linear",
      backgroundOpacity: "100"
    },

    {
      id: "fire",
      name: "Fire",
      category: "creative",
      icon: "▲",
      description: "Rosso fuoco e arancio brillante.",
      dotsType: "extra-rounded",
      dotsColor1: "#8A0E00",
      dotsColor2: "#FF8A00",
      gradientType: "linear",
      gradientRotation: "45",
      cornersSquareType: "extra-rounded",
      cornersDotType: "dot",
      cornersColor1: "#670900",
      cornersColor2: "#FFAA1F",
      useCornersGradient: true,
      backgroundColor1: "#FFFFFF",
      backgroundColor2: "#FFF3E7",
      backgroundGradientType: "radial",
      backgroundOpacity: "100"
    },

    {
      id: "galaxy",
      name: "Galaxy",
      category: "creative",
      icon: "✺",
      description: "Blu cosmico e viola elettrico.",
      dotsType: "classy-rounded",
      dotsColor1: "#11125C",
      dotsColor2: "#A343FF",
      gradientType: "radial",
      gradientRotation: "0",
      cornersSquareType: "extra-rounded",
      cornersDotType: "dot",
      cornersColor1: "#0B0B3F",
      cornersColor2: "#C36CFF",
      useCornersGradient: true,
      backgroundColor1: "#FFFFFF",
      backgroundColor2: "#F5EEFF",
      backgroundGradientType: "radial",
      backgroundOpacity: "100"
    },

    {
      id: "candy",
      name: "Candy",
      category: "creative",
      icon: "●",
      description: "Rosa candy e viola per brand giocosi.",
      dotsType: "rounded",
      dotsColor1: "#FF3CAC",
      dotsColor2: "#784BA0",
      gradientType: "linear",
      gradientRotation: "60",
      cornersSquareType: "extra-rounded",
      cornersDotType: "dot",
      cornersColor1: "#DF218D",
      cornersColor2: "#9262C2",
      useCornersGradient: true,
      backgroundColor1: "#FFFFFF",
      backgroundColor2: "#FFF1FC",
      backgroundGradientType: "radial",
      backgroundOpacity: "100"
    },

    {
      id: "terra",
      name: "Terra",
      category: "creative",
      icon: "◒",
      description: "Terracotta e oro per tour e resort.",
      dotsType: "classy",
      dotsColor1: "#7F2D20",
      dotsColor2: "#D09A32",
      gradientType: "linear",
      gradientRotation: "50",
      cornersSquareType: "extra-rounded",
      cornersDotType: "dot",
      cornersColor1: "#682117",
      cornersColor2: "#E3B747",
      useCornersGradient: true,
      backgroundColor1: "#FFFDF9",
      backgroundColor2: "#FFF0DE",
      backgroundGradientType: "radial",
      backgroundOpacity: "100"
    },

    {
      id: "sunset",
      name: "Sunset",
      category: "creative",
      icon: "☀",
      description: "Magenta e arancio da hospitality.",
      dotsType: "dots",
      dotsColor1: "#8F1D7A",
      dotsColor2: "#FF7B24",
      gradientType: "linear",
      gradientRotation: "45",
      cornersSquareType: "extra-rounded",
      cornersDotType: "dot",
      cornersColor1: "#80175E",
      cornersColor2: "#FF6824",
      useCornersGradient: true,
      backgroundColor1: "#FFFFFF",
      backgroundColor2: "#FFF0E8",
      backgroundGradientType: "linear",
      backgroundOpacity: "100"
    },

    {
      id: "ice",
      name: "Ice",
      category: "creative",
      icon: "❄",
      description: "Blu ghiaccio leggero e brillante.",
      dotsType: "dots",
      dotsColor1: "#1D4E89",
      dotsColor2: "#67D8F4",
      gradientType: "linear",
      gradientRotation: "120",
      cornersSquareType: "dot",
      cornersDotType: "dot",
      cornersColor1: "#183F70",
      cornersColor2: "#76E2FA",
      useCornersGradient: true,
      backgroundColor1: "#FFFFFF",
      backgroundColor2: "#ECFBFF",
      backgroundGradientType: "radial",
      backgroundOpacity: "100"
    },

    {
      id: "laser-mint",
      name: "Laser Mint",
      category: "creative",
      icon: "✦",
      description: "Turchese laser e menta brillante.",
      dotsType: "dots",
      dotsColor1: "#006E7F",
      dotsColor2: "#30F0B1",
      gradientType: "linear",
      gradientRotation: "65",
      cornersSquareType: "dot",
      cornersDotType: "dot",
      cornersColor1: "#005564",
      cornersColor2: "#42FFC4",
      useCornersGradient: true,
      backgroundColor1: "#FFFFFF",
      backgroundColor2: "#E9FFF8",
      backgroundGradientType: "radial",
      backgroundOpacity: "100"
    },

    {
      id: "ultraviolet",
      name: "Ultraviolet",
      category: "creative",
      icon: "✧",
      description: "Viola profondo e blu elettrico.",
      dotsType: "classy-rounded",
      dotsColor1: "#2D0B59",
      dotsColor2: "#3C9DFF",
      gradientType: "linear",
      gradientRotation: "125",
      cornersSquareType: "extra-rounded",
      cornersDotType: "dot",
      cornersColor1: "#20063F",
      cornersColor2: "#55AEFF",
      useCornersGradient: true,
      backgroundColor1: "#FFFFFF",
      backgroundColor2: "#EEF4FF",
      backgroundGradientType: "radial",
      backgroundOpacity: "100"
    },

    {
      id: "cosmic",
      name: "Cosmic",
      category: "creative",
      icon: "✹",
      description: "Viola scuro e arancio per nightlife.",
      dotsType: "classy",
      dotsColor1: "#301050",
      dotsColor2: "#FF7A18",
      gradientType: "linear",
      gradientRotation: "35",
      cornersSquareType: "extra-rounded",
      cornersDotType: "dot",
      cornersColor1: "#22083D",
      cornersColor2: "#FF913B",
      useCornersGradient: true,
      backgroundColor1: "#FFFFFF",
      backgroundColor2: "#FFF3E9",
      backgroundGradientType: "radial",
      backgroundOpacity: "100"
    }
  ]
};